<def f='include/c++/12/future' l='1140' ll='1142' type='void std::promise::set_exception(std::__exception_ptr::exception_ptr __p)'/>
